/* tslint:disable */
/* eslint-disable */
/**
 * Queue Service - OpenAPI 3.0
 * Queues the conversations to be handled by available agents.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ano@dixa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

