openapi: 3.0.2
info:
  contact:
    email: ano@dixa.com
  description: Service for deploying services onto Kubernetes.
  title: K8s Deployer - OpenAPI 3.0
  version: 0.0.1
servers:
- url: http://k8s-deployer
- url: http://localhost:8080
paths:
  /redeployAll:
    get:
      operationId: redeployAll
      responses:
        "200":
          description: Successfuly operation
      summary: Redeploys all services to their latest image.
      x-eov-operation-handler: controllers/DefaultController
  /deploy/chaosTest:
    post:
      operationId: deployChaosTest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChaosRun'
        description: Specification for the Chaos Test to be deployed
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: Successful operation
        "404":
          description: Test not found
      summary: Deploy a Chaos Test per its specification.
      x-eov-operation-handler: controllers/DefaultController
components:
  schemas:
    ChaosRun:
      example:
        routingSpec:
          routingType: split
          weight: 0.8008281904610115
        runId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        runId:
          format: uuid
          type: string
        mode:
          $ref: '#/components/schemas/DeploymentMode'
        routingSpec:
          $ref: '#/components/schemas/RoutingSpec'
    DeploymentMode:
      description: Mode of the deployment to be made
      enum:
      - canary
      - production
      type: string
    RoutingSpec:
      example:
        routingType: split
        weight: 0.8008281904610115
      properties:
        routingType:
          description: The way in which traffic is meant to be routed to the canary
            environment. Split - migrates portion of traffic from primary environment
            to canary. Mirror - mirrors portion of the traffic from the primary to
            canary environment.
          enum:
          - split
          - mirror
          type: string
        weight:
          description: The percentage of total traffic to be routed to the canary
            environment.
          type: number
      type: object
    inline_response_200:
      example:
        result: result
        namespace: namespace
        runId: runId
      properties:
        result:
          type: string
        runId:
          type: string
        namespace:
          type: string
      type: object
