openapi: 3.0.2
servers:
  - url: http://localhost:8081/v1
info:
  description: |-
    Message service handles messages for conversations in Dixa.
  version: 0.0.1
  title: Messages Service - OpenAPI 3.0
  contact:
    email: ano@dixa.com
tags:
  - name: messages
    description: Everything about Messages of Conversations
paths:
  /messages:
    get:
      summary: Get all Messages
      operationId: getMessages
      responses:
        "200":
          description: Successfuly operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Messages"
  /message:
    post:
      tags:
        - messages
      summary: Add a new Message
      description: Add a new Message
      operationId: addMessage
      responses:
        "200":
          description: Successful operation
        "400":
          description: Invalid input
      requestBody:
        description: Create a new Message
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Message"
  /message/${id}:
    get:
      summary: Get a single message
      operationId: getMessage
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of a Message
          example: "e0064a57-b327-4f77-82d7-8042911613e8"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "404":
          description: Message Not Found
    delete:
      summary: Delete a single Message
      operationId: deleteMessage
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of a Message
          example: "e0064a57-b327-4f77-82d7-8042911613e8"
      responses:
        "200":
          description: Successful operation
        "404":
          description: Message Not Found
components:
  schemas:
    Message:
      properties:
        id:
          type: string
          format: uuid
          example: "afd75b5e-d323-40c6-a8e9-1557cbf8f5bb"
        direction:
          type: string
          description: Direction in which the message was sent
          enum:
            - inbound
            - outbound
        created_at:
          type: string
          format: date-time
          example: "2017-07-21T17:32:28Z"
        initial_channel:
          type: string
          description: Channel that originated the Conversation
          enum:
            - widget
            - telephony
            - email
            - whatsapp
            - messenger
          example: widget
    Messages:
      type: array
      items:
        $ref: "#/components/schemas/Message"
