apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: conversation-service
spec:
  host: conversation-service.default.svc.clusters.local
  subsets:
    - name: production
      labels:
        deployment-type: production
