apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: conversation-service
spec:
  hosts:
  - conversation-service.default.svc.cluster.local
  http:
  - name: production
    route:
    - destination:
        host: conversation-service.svc.cluster.local
        subset: production
    # retries:
    #   attempts: 3
    #   perTryTimeout: 2s
    #   retryOn: 5xx
    # # fault:
    #   delay:
    #     percentage:
    #       value: 0.1
    #     fixedDelay: 2s
    #   abort:
    #     percentage:
    #       value: 0.1
    #     httpStatus: 500
