apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  labels:
    dixa-app: loadgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      dixa-app: loadgenerator 
  template:
    metadata:
      name: loadgenerator
      labels:
        dixa-app: loadgenerator
    spec:
      containers:
      - name: loadgenerator
        image: 654015427134.dkr.ecr.eu-west-1.amazonaws.com/chaos-secalekdev-loadgenerator:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 64Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 1000m
        env:
          - name: KILLSWITCH
            value: "OFF"
