apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: message-service
spec:
  hosts:
  - message-service
  http:
  - name: 'production'
    route:
    - destination:
        host: message-service
      weight: 100
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: 5xx
    fault:
      abort:
        percentage:
          value: 10
        httpStatus: 500
    # mirror:
    #   host: message-service.svc.cluster.local
    #   subset: chaos-canary
    # mirrorPercentage: 
    #   value: 10
    # fault:
    #   delay:
    #     percentage:
    #       value: 0.1
    #     fixedDelay: 2s
    
