openapi: 3.0.2
info:
  contact:
    email: ano@dixa.com
  description: Queues the conversations to be handled by available agents.
  title: Queue Service - OpenAPI 3.0
  version: 0.0.1
servers:
- url: http://queue-service/v1
paths:
  /queues:
    get:
      operationId: getQueues
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Queues'
          description: Successful operation
      summary: Get all available Queues
      x-eov-operation-handler: controllers/DefaultController
  /queue:
    post:
      operationId: addQueue
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Queue'
        description: Create a new Queue
        required: true
      responses:
        "200":
          description: Successful operation
        "400":
          description: Invalid input
      summary: Add a new Queue
      x-eov-operation-handler: controllers/DefaultController
  /queue/{id}:
    get:
      operationId: getQueue
      parameters:
      - description: ID of a Queue in which to put the conversation
        example: e0064a57-b327-4f77-82d7-8042911613e8
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful Operation
        "404":
          description: Queue Not Found
      summary: Get a single Queue
      x-eov-operation-handler: controllers/DefaultController
  /queue/{id}/conversation:
    post:
      operationId: addConversationToQueue
      parameters:
      - description: ID of a Queue in which to put the conversation
        example: e0064a57-b327-4f77-82d7-8042911613e8
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueuedConversation'
        description: Create a new Queue
        required: true
      responses:
        "200":
          description: Successful operation
        "400":
          description: Invalid input
      summary: Add a Conversation to the Queue
      x-eov-operation-handler: controllers/DefaultController
components:
  schemas:
    Queue:
      example:
        created_at: 2017-07-21T17:32:28Z
        offer_algorithm: oneAtATimeRandom
        id: f41b9796-a630-4d3e-9fd9-8be78373a48f
      properties:
        id:
          example: f41b9796-a630-4d3e-9fd9-8be78373a48f
          format: uuid
          type: string
        created_at:
          example: 2017-07-21T17:32:28Z
          format: date-time
          type: string
        offer_algorithm:
          description: Algorithm used to offer services
          enum:
          - oneAtATimeRandom
          type: string
    Queues:
      items:
        $ref: '#/components/schemas/Queue'
      type: array
    QueuedConversation:
      description: A conversation to be offered.
      example:
        isLive: true
        conversation_id: e0064a57-b327-4f77-82d7-8042911613e8
        channel: widget
        created_at: 2017-07-21T17:32:28Z
        id: e0064a57-b327-4f77-82d7-8042911613e8
      properties:
        id:
          example: e0064a57-b327-4f77-82d7-8042911613e8
          format: uuid
          type: string
        conversation_id:
          example: e0064a57-b327-4f77-82d7-8042911613e8
          format: uuid
          type: string
        isLive:
          description: Whether the conversation has been offered to an agent already
            or not.
          type: boolean
        created_at:
          example: 2017-07-21T17:32:28Z
          format: date-time
          type: string
        channel:
          enum:
          - widget
          - telephony
          - email
          - whatsapp
          - messenger
          type: string
