openapi: 3.0.2
servers:
  - url: http://k8s-deployer
info:
  description: |-
    Service for deploying services onto Kubernetes.
  version: 0.0.1
  title: K8s Deployer - OpenAPI 3.0
  contact:
    email: ano@dixa.com
paths:
  /redeployAll:
    get:
      summary: Redeploys all services to their latest image.
      operationId: redeployAll
      responses:
        "200":
          description: Successfuly operation
  /deploy/chaosTest:
    post:
      summary: Deploy a Chaos Test per its specification.
      operationId: deployChaosTest
      requestBody:
        description: Specification for the Chaos Test to be deployed 
        content:
          application/json:
              schema:
                $ref: "#/components/schemas/ChaosRun"
      responses:
        "200":
          description: Successful operation
        "404":
          description: Test not found
components:
  schemas:
    ChaosRun:
      properties:
        runId:
          type: string
          format: uuid
        mode:
          type: string
          description: Mode of the deployment to be made
          enum:
              - canary
              - production
