openapi: 3.0.2
servers:
  - url: http://k8s-deployer
  - url: http://localhost:8080
info:
  description: |-
    Service for deploying services onto Kubernetes.
  version: 0.0.1
  title: K8s Deployer - OpenAPI 3.0
  contact:
    email: ano@dixa.com
paths:
  /redeployAll:
    get:
      summary: Redeploys all services to their latest image.
      operationId: redeployAll
      responses:
        "200":
          description: Successfuly operation
  /deploy/chaosTest:
    post:
      summary: Deploy a Chaos Test per its specification.
      operationId: deployChaosTest
      requestBody:
        description: Specification for the Chaos Test to be deployed
        required: true
        content:
          application/json:
              schema:
                $ref: "#/components/schemas/ChaosRun"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                  runId:
                    type: string
                  namespace:
                    type: string
        "404":
          description: Test not found
components:
  schemas:
    ChaosRun:
      properties:
        runId:
          type: string
          format: uuid
        mode:
          $ref: "#/components/schemas/DeploymentMode"
        routingSpec:
          $ref: "#/components/schemas/RoutingSpec"
    DeploymentMode:
      type: string
      description: Mode of the deployment to be made
      enum:
          - canary
          - production
    RoutingSpec:
      type: object
      properties:
        routingType:
          type: string
          description: The way in which traffic is meant to be routed to the canary environment. Split - migrates portion of traffic from primary environment to canary. Mirror - mirrors portion of the traffic from the primary to canary environment.
          enum:
            - split
            - mirror
        weight:
          description: The percentage of total traffic to be routed to the canary environment.
          type: number
