/* tslint:disable */
/* eslint-disable */
/**
 * K8s Deployer - OpenAPI 3.0
 * Service for deploying services onto Kubernetes.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ano@dixa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

